OUTPUT_DIR: "work_dirs/efficientnet-b5"
MODEL:
  NAME: "efficientnet-b5"
  NUM_CLASSES: 5

SOLVER:
  IMS_PER_GPU: 4
  MAX_ITER: 100000
  STEPS: [60000, 90000]
  BASE_LR: 0.001

DATA:
  INPUT_SIZE: 456
  BRIGHTNESS: 0.05
  CONTRAST: 0.1
  SATURATION: 0.05
  HUE: 0.005
  ROTATION_DEGREES: 120
  CATEGORY_LOSS_WEIGHT: [2, 15, 7, 50, 50]
  PIXEL_MEAN: [109.9776, 75.7212, 52.5703]
  PIXEL_STD: [0.2742, 0.1994, 0.1680]

TEST:
  IMS_PER_GPU: 4