OUTPUT_DIR: "work_dirs/wsl_resnext"
MODEL:
  NAME: "resnext101_32x32d"
  NUM_CLASSES: 5

SOLVER:
  IMS_PER_GPU: 2
  MAX_ITER: 100000
  STEPS: [60000, 90000]
  BASE_LR: 0.001

DATA:
  INPUT_SIZE: 448
  BRIGHTNESS: 0.05
  CONTRAST: 0.1
  SATURATION: 0.05
  HUE: 0.005
  ROTATION_DEGREES: 120
  CATEGORY_LOSS_WEIGHT: [2, 15, 7, 50, 50]

TEST:
  IMS_PER_GPU: 2